name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install

    - name: Build the project
      run: |
        npx webpack

    # Add the GitHub Pages deployment step
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # The branch where you want to deploy the site (can be 'gh-pages')
        target_branch: gh-pages
        # The folder that contains the built files (make sure this matches your build output folder)
        source_dir: dist
        # GitHub token, use the default token provided by GitHub Actions
        token: ${{ secrets.GITHUB_TOKEN }}
